# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-12 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asientos',
            name='asiento',
            field=models.CharField(max_length=2),
        ),
    ]
